// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"

	"github.com/oklog/ulid/v2"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for DrawGameRequestAction.
const (
	ACCEPT  DrawGameRequestAction = "accept"
	DECLINE DrawGameRequestAction = "decline"
	OFFER   DrawGameRequestAction = "offer"
)

// Defines values for EndGameRequestEndedBy.
const (
	EndGameRequestEndedByDRAW        EndGameRequestEndedBy = "draw"
	EndGameRequestEndedByMATE        EndGameRequestEndedBy = "mate"
	EndGameRequestEndedByRESIGNATION EndGameRequestEndedBy = "resignation"
	EndGameRequestEndedByTIMEOUT     EndGameRequestEndedBy = "timeout"
)

// Defines values for EndGameRequestWinner.
const (
	EndGameRequestWinnerBLACK EndGameRequestWinner = "black"
	EndGameRequestWinnerDRAW  EndGameRequestWinner = "draw"
	EndGameRequestWinnerWHITE EndGameRequestWinner = "white"
)

// Defines values for GameEndedBy.
const (
	GameEndedByDRAW        GameEndedBy = "draw"
	GameEndedByMATE        GameEndedBy = "mate"
	GameEndedByRESIGNATION GameEndedBy = "resignation"
	GameEndedByTIMEOUT     GameEndedBy = "timeout"
)

// Defines values for GameMode.
const (
	GameModeBLITZ     GameMode = "blitz"
	GameModeCLASSICAL GameMode = "classical"
	GameModeRAPID     GameMode = "rapid"
)

// Defines values for GameTimeframe.
const (
	N1  GameTimeframe = 1
	N10 GameTimeframe = 10
	N3  GameTimeframe = 3
	N30 GameTimeframe = 30
	N5  GameTimeframe = 5
)

// Defines values for GameWinner.
const (
	GameWinnerBLACK GameWinner = "black"
	GameWinnerDRAW  GameWinner = "draw"
	GameWinnerWHITE GameWinner = "white"
)

// Defines values for NewGameRequestMode.
const (
	NewGameRequestModeBLITZ     NewGameRequestMode = "blitz"
	NewGameRequestModeCLASSICAL NewGameRequestMode = "classical"
	NewGameRequestModeRAPID     NewGameRequestMode = "rapid"
)

// Defines values for GamesListParamsStatus.
const (
	ACTIVE   GamesListParamsStatus = "active"
	FINISHED GamesListParamsStatus = "finished"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// AccessToken JWT access token
	AccessToken string `json:"accessToken"`

	// ExpiresIn Token valid in seconds
	ExpiresIn *int `json:"expiresIn,omitempty"`

	// TokenType Token type for Authorization header
	TokenType string `json:"tokenType"`
}

// Board defines model for Board.
type Board struct {
	Fen       string `json:"fen"`
	GameId    ULID   `json:"gameId"`
	MoveCount int    `json:"moveCount"`
}

// DrawGameRequest defines model for DrawGameRequest.
type DrawGameRequest struct {
	Action DrawGameRequestAction `json:"action"`
	GameId ULID                  `json:"gameId"`
}

// DrawGameRequestAction defines model for DrawGameRequest.Action.
type DrawGameRequestAction string

// EndGameRequest defines model for EndGameRequest.
type EndGameRequest struct {
	EndedBy EndGameRequestEndedBy `json:"endedBy"`
	GameId  ULID                  `json:"gameId"`
	Winner  EndGameRequestWinner  `json:"winner"`
}

// EndGameRequestEndedBy defines model for EndGameRequest.EndedBy.
type EndGameRequestEndedBy string

// EndGameRequestWinner defines model for EndGameRequest.Winner.
type EndGameRequestWinner string

// ErrorBadRequest defines model for ErrorBadRequest.
type ErrorBadRequest struct {
	ErrorMessage *string `json:"errorMessage,omitempty"`
	StatusCode   *int    `json:"statusCode,omitempty"`
}

// ErrorForbidden defines model for ErrorForbidden.
type ErrorForbidden struct {
	ErrorMessage *string `json:"errorMessage,omitempty"`
	StatusCode   *int    `json:"statusCode,omitempty"`
}

// ErrorNotFound defines model for ErrorNotFound.
type ErrorNotFound struct {
	ErrorMessage *string `json:"errorMessage,omitempty"`
	StatusCode   *int    `json:"statusCode,omitempty"`
}

// ErrorUnauthorized defines model for ErrorUnauthorized.
type ErrorUnauthorized struct {
	ErrorMessage *string `json:"errorMessage,omitempty"`
	StatusCode   *int    `json:"statusCode,omitempty"`
}

// Game defines model for Game.
type Game struct {
	BlackUserId ULID           `json:"blackUserId"`
	EndAt       *time.Time     `json:"endAt,omitempty"`
	Ended       bool           `json:"ended"`
	EndedBy     *GameEndedBy   `json:"endedBy,omitempty"`
	Id          ULID           `json:"id"`
	Mode        GameMode       `json:"mode"`
	Rated       bool           `json:"rated"`
	StartAt     *time.Time     `json:"startAt,omitempty"`
	Timeframe   *GameTimeframe `json:"timeframe,omitempty"`
	WhiteUserId ULID           `json:"whiteUserId"`
	Winner      *GameWinner    `json:"winner,omitempty"`
}

// GameEndedBy defines model for Game.EndedBy.
type GameEndedBy string

// GameMode defines model for Game.Mode.
type GameMode string

// GameTimeframe defines model for Game.Timeframe.
type GameTimeframe int

// GameWinner defines model for Game.Winner.
type GameWinner string

// GameHistory defines model for GameHistory.
type GameHistory struct {
	Games  []Game `json:"games"`
	Limit  *int   `json:"limit,omitempty"`
	Offset *int   `json:"offset,omitempty"`
	Total  int    `json:"total"`
}

// LegalMovesList defines model for LegalMovesList.
type LegalMovesList struct {
	Moves []MoveRequest `json:"moves"`
}

// Move defines model for Move.
type Move struct {
	From      string  `json:"from"`
	GameId    ULID    `json:"gameId"`
	Id        ULID    `json:"id"`
	Promotion *string `json:"promotion,omitempty"`
	To        string  `json:"to"`
}

// MoveHistory defines model for MoveHistory.
type MoveHistory struct {
	GameId ULID   `json:"gameId"`
	Moves  []Move `json:"moves"`
}

// MoveRequest defines model for MoveRequest.
type MoveRequest struct {
	From      string  `json:"from"`
	GameId    ULID    `json:"gameId"`
	Promotion *string `json:"promotion,omitempty"`
	To        string  `json:"to"`
}

// NewGameRequest defines model for NewGameRequest.
type NewGameRequest struct {
	Mode       NewGameRequestMode `json:"mode"`
	OpponentId *ULID              `json:"opponentId,omitempty"`
	Rated      bool               `json:"rated"`
}

// NewGameRequestMode defines model for NewGameRequest.Mode.
type NewGameRequestMode string

// OkResponse defines model for OkResponse.
type OkResponse struct {
	Ok bool `json:"ok"`
}

// ResignGameRequest defines model for ResignGameRequest.
type ResignGameRequest struct {
	GameId ULID `json:"gameId"`
}

// ScoreRequest defines model for ScoreRequest.
type ScoreRequest struct {
	Fen string `json:"fen"`
}

// ScoreResponse defines model for ScoreResponse.
type ScoreResponse struct {
	Score float32 `json:"score"`
}

// ULID defines model for ULID.
type ULID = ulid.ULID

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        ULID      `json:"id"`
	Rating    int       `json:"rating"`
	Username  string    `json:"username"`
}

// UserAuthRequest defines model for UserAuthRequest.
type UserAuthRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// WithId defines model for WithId.
type WithId struct {
	Id ULID `json:"id"`
}

// XRequestID defines model for XRequestID.
type XRequestID = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorBadRequest

// Forbidden defines model for Forbidden.
type Forbidden = ErrorForbidden

// NotFound defines model for NotFound.
type NotFound = ErrorNotFound

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorUnauthorized

// BoardGetStateParams defines parameters for BoardGetState.
type BoardGetStateParams struct {
	GameId    ULID `form:"gameId" json:"gameId"`
	MoveCount *int `form:"moveCount,omitempty" json:"moveCount,omitempty"`

	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// GetLegalMovesParams defines parameters for GetLegalMoves.
type GetLegalMovesParams struct {
	PieceAddress string `form:"pieceAddress" json:"pieceAddress"`

	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// MoveValidateParams defines parameters for MoveValidate.
type MoveValidateParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// ScoreGetParams defines parameters for ScoreGet.
type ScoreGetParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// DrawParams defines parameters for Draw.
type DrawParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// GameFinishParams defines parameters for GameFinish.
type GameFinishParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// MoveCreateParams defines parameters for MoveCreate.
type MoveCreateParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// GameCreateParams defines parameters for GameCreate.
type GameCreateParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// ResignParams defines parameters for Resign.
type ResignParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// MoveListParams defines parameters for MoveList.
type MoveListParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// GameGetParams defines parameters for GameGet.
type GameGetParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// HealthParams defines parameters for Health.
type HealthParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// LoginParams defines parameters for Login.
type LoginParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// GetMeParams defines parameters for GetMe.
type GetMeParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// RegisterParams defines parameters for Register.
type RegisterParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// GamesListParams defines parameters for GamesList.
type GamesListParams struct {
	Status *GamesListParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                   `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                   `form:"offset,omitempty" json:"offset,omitempty"`

	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// GamesListParamsStatus defines parameters for GamesList.
type GamesListParamsStatus string

// MoveValidateJSONRequestBody defines body for MoveValidate for application/json ContentType.
type MoveValidateJSONRequestBody = MoveRequest

// ScoreGetJSONRequestBody defines body for ScoreGet for application/json ContentType.
type ScoreGetJSONRequestBody = ScoreRequest

// DrawJSONRequestBody defines body for Draw for application/json ContentType.
type DrawJSONRequestBody = DrawGameRequest

// GameFinishJSONRequestBody defines body for GameFinish for application/json ContentType.
type GameFinishJSONRequestBody = EndGameRequest

// MoveCreateJSONRequestBody defines body for MoveCreate for application/json ContentType.
type MoveCreateJSONRequestBody = MoveRequest

// GameCreateJSONRequestBody defines body for GameCreate for application/json ContentType.
type GameCreateJSONRequestBody = NewGameRequest

// ResignJSONRequestBody defines body for Resign for application/json ContentType.
type ResignJSONRequestBody = ResignGameRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = UserAuthRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = UserAuthRequest
